openapi: 3.0.3
info:
  title: M5 - Projeto Final - Kanvas
  version: 1.0.0
  description: Seu chefe passou uma nova demanda para você, ele deseja que seja desenvolvida
    uma API Rest para o gerenciamento de cursos e aulas de uma escola de modalidade
    EAD. Para direcionar melhor você, é passado o DER (Diagrama de Entidade e Relacionamento)
    da aplicação que deve ser seguido.
paths:
  /api/accounts/:
    get:
      operationId: accounts_list
      tags:
      - accounts
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
          description: ''
    post:
      operationId: accounts_create
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Account'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Account'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
          description: ''
  /api/courses/:
    get:
      operationId: courses_list
      tags:
      - courses
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'
          description: ''
    post:
      operationId: courses_create
      tags:
      - courses
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Course'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Course'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
          description: ''
  /api/courses/{course_id}/:
    get:
      operationId: courses_retrieve
      parameters:
      - in: path
        name: course_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - courses
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
          description: ''
    put:
      operationId: courses_update
      parameters:
      - in: path
        name: course_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - courses
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Course'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Course'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
          description: ''
    patch:
      operationId: courses_partial_update
      parameters:
      - in: path
        name: course_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - courses
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedCourse'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedCourse'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedCourse'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
          description: ''
    delete:
      operationId: courses_destroy
      parameters:
      - in: path
        name: course_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - courses
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/courses/{course_id}/contents/:
    post:
      operationId: courses_contents_create
      parameters:
      - in: path
        name: course_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - courses
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Content'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Content'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Content'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Content'
          description: ''
  /api/courses/{course_id}/contents/{content_id}/:
    get:
      operationId: courses_contents_retrieve
      parameters:
      - in: path
        name: content_id
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: course_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - courses
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Content'
          description: ''
    put:
      operationId: courses_contents_update
      parameters:
      - in: path
        name: content_id
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: course_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - courses
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Content'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Content'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Content'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Content'
          description: ''
    patch:
      operationId: courses_contents_partial_update
      parameters:
      - in: path
        name: content_id
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: course_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - courses
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedContent'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedContent'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedContent'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Content'
          description: ''
    delete:
      operationId: courses_contents_destroy
      parameters:
      - in: path
        name: content_id
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: course_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - courses
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/courses/{course_id}/students/:
    get:
      operationId: courses_students_retrieve
      parameters:
      - in: path
        name: course_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - courses
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourseStudent'
          description: ''
    put:
      operationId: courses_students_update
      parameters:
      - in: path
        name: course_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - courses
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CourseStudent'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CourseStudent'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CourseStudent'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourseStudent'
          description: ''
    patch:
      operationId: courses_students_partial_update
      parameters:
      - in: path
        name: course_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - courses
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedCourseStudent'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedCourseStudent'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedCourseStudent'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourseStudent'
          description: ''
  /api/courses/{course_id}/students/{student_id}/:
    delete:
      operationId: courses_students_destroy
      parameters:
      - in: path
        name: course_id
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: student_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - courses
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/login/:
    post:
      operationId: login_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        email:
          type: string
          format: email
          maxLength: 100
        username:
          type: string
          maxLength: 150
        is_superuser:
          type: boolean
        password:
          type: string
          writeOnly: true
          maxLength: 128
      required:
      - email
      - id
      - password
      - username
    Content:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 150
        content:
          type: string
        video_url:
          type: string
          nullable: true
          maxLength: 200
      required:
      - content
      - id
      - name
    Course:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 100
        status:
          $ref: '#/components/schemas/CourseStatusEnum'
        start_date:
          type: string
          format: date
        end_date:
          type: string
          format: date
        instructor:
          type: string
          format: uuid
          nullable: true
        students_courses:
          type: array
          items:
            $ref: '#/components/schemas/StudentCourse'
          readOnly: true
        contents:
          type: array
          items:
            $ref: '#/components/schemas/Content'
          readOnly: true
      required:
      - contents
      - end_date
      - id
      - name
      - start_date
      - students_courses
    CourseStatusEnum:
      enum:
      - not started
      - in progress
      - finished
      type: string
      description: |-
        * `not started` - not started
        * `in progress` - in progress
        * `finished` - finished
    CourseStudent:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          readOnly: true
        students_courses:
          type: array
          items:
            $ref: '#/components/schemas/StudentCourse'
      required:
      - id
      - name
      - students_courses
    PatchedContent:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 150
        content:
          type: string
        video_url:
          type: string
          nullable: true
          maxLength: 200
    PatchedCourse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 100
        status:
          $ref: '#/components/schemas/CourseStatusEnum'
        start_date:
          type: string
          format: date
        end_date:
          type: string
          format: date
        instructor:
          type: string
          format: uuid
          nullable: true
        students_courses:
          type: array
          items:
            $ref: '#/components/schemas/StudentCourse'
          readOnly: true
        contents:
          type: array
          items:
            $ref: '#/components/schemas/Content'
          readOnly: true
    PatchedCourseStudent:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          readOnly: true
        students_courses:
          type: array
          items:
            $ref: '#/components/schemas/StudentCourse'
    StudentCourse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        student_id:
          type: string
          format: uuid
          readOnly: true
        student_username:
          type: string
          readOnly: true
        student_email:
          type: string
          format: email
        status:
          $ref: '#/components/schemas/StudentCourseStatusEnum'
      required:
      - id
      - student_email
      - student_id
      - student_username
    StudentCourseStatusEnum:
      enum:
      - pending
      - accepted
      type: string
      description: |-
        * `pending` - Pending
        * `accepted` - Accepted
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - password
      - refresh
      - username
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
